name: Docker Run Advent of Code CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run docker-run.sh with "--all"
      run: bash docker-run.sh --all
